#import "../10b.credits/portraits.asm"

// this file generates a binary blob with the compressed scrolling gfx data for loading afterwards
// also a .pef end .efo file will be generated by make, which we don't need.. 

.label firstByte    = $8000+(width*height*10)
.label gfxData      = $8000+(width*height*10)

// we do not need any spindle header.. but let's make it compatible with the other parts.
#if AS_SPINDLE_PART
  .label spindleLoadAddress = firstByte
  *=spindleLoadAddress-18-0-3 "Spindle header"
  .label spindleHeaderStart = *

    .text "EFO2"        // fileformat magic
    .word 0             // prepare routine
    .word 0             // setup routine
    .word 0             // irq handler
    .word 0             // main routine
    .word 0             // fadeout routine
    .word 0             // cleanup routine
    .word 0             // location of playroutine call

    .byte 0
    .word spindleLoadAddress    // Load address

  .label spindleHeaderEnd = *
  .var efoHeaderSize = spindleHeaderEnd-spindleHeaderStart
#endif

// put portraits into memory
* = gfxData "[GFX] picture 1 data"
.fill data1.size(), data1.get(i)
.fill data2.size(), data2.get(i)
.fill data3.size(), data3.get(i)