// this file generates a binary blob with the compressed scrolling gfx data for loading afterwards
// also a .pef end .efo file will be generated by make, which we don't need.. 

#import "../03c.greetings/convert.asm"  // convert scroll gfx to import d021/d022/d023 tables
#import "../03c.greetings/convert2.asm" // convert gfx into usable format.

.label firstByte    = $2000
.label gfxData      = $2000

.const sinSizeDiffed = 128

// we do not need any spindle header.. but let's make it compatible with the other parts.
#if AS_SPINDLE_PART
  .label spindleLoadAddress = firstByte
  *=spindleLoadAddress-18-0-3 "Spindle header"
  .label spindleHeaderStart = *

    .text "EFO2"        // fileformat magic
    .word 0             // prepare routine
    .word 0             // setup routine
    .word 0             // irq handler
    .word 0             // main routine
    .word 0             // fadeout routine
    .word 0             // cleanup routine
    .word 0             // location of playroutine call

    .byte 0
    .word spindleLoadAddress    // Load address

  .label spindleHeaderEnd = *
  .var efoHeaderSize = spindleHeaderEnd-spindleHeaderStart
#endif

* = gfxData

// put all graham data in memory
.fill grahamData.size(), grahamData.get(i)
//.fill 512,$ff  // empty line
.fill 512,$ff  // and another empty line

// add color tables
* = * "[DATA] d021 table"
  .fill lstD021.size()-26, lstD021.get(i) + ((lstD022.get(i))*16)
  .fill 26, 0

* = * "[DATA] d022 table"
  .fill lstD023.size()-26, lstD023.get(i)
  .fill 26, 0
