// this file generates a binary blob with the compressed scrolling gfx data for loading afterwards
// also a .pef end .efo file will be generated by make, which we don't need.. 

#import "../03c.greetings/convert.asm" // convert gfx into usable format.

.label firstByte    = $2000
.label gfxData      = $2000

// we do not need any spindle header.. but let's make it compatible with the other parts.
#if AS_SPINDLE_PART
  .label spindleLoadAddress = firstByte
  *=spindleLoadAddress-18-0-3 "Spindle header"
  .label spindleHeaderStart = *

    .text "EFO2"        // fileformat magic
    .word 0             // prepare routine
    .word 0             // setup routine
    .word 0             // irq handler
    .word 0             // main routine
    .word 0             // fadeout routine
    .word 0             // cleanup routine
    .word 0             // location of playroutine call

    .byte 0
    .word spindleLoadAddress    // Load address

  .label spindleHeaderEnd = *
  .var efoHeaderSize = spindleHeaderEnd-spindleHeaderStart
#endif

* = gfxData

.var gfxPositions = List(); .for (var i=0; i<8*16; i++) { .eval gfxPositions.add(gfxData+i*$100) }

// put all compressed graphics in memory
.for (var p=0; p<gfxPositions.size(); p++)
{
  .var currentPosition = gfxPositions.get(p)
  .if (currentPosition!=*)
  {
    *=currentPosition "[DATA] gfx compressed data"   // set new memory position
  }

  .fill $100, lstGfx.get(i+p*$100)                   // fill with data
}
