:BasicUpstart2(code)

* = $1000
code:
{
  sei
  lda #$35
  sta $01

  lda #$01
  sta $d019
  sta $d01a
  sta $dc0d
  lda #<irq
  sta $fffe
  lda #>irq
  sta $ffff
  lda #$fa
  sta $d012
  lda #$1b
  sta $d011

  lda #$7f
  sta $dc0d               //disable timer interrupts which can be generated by the two CIA chips
  sta $dd0d               //the kernal uses such an interrupt to flash the cursor and scan the keyboard, so we better
                          //stop it.
  lda $dc0d               //by reading this two registers we negate any pending CIA irqs.
  lda $dd0d               //if we don't do this, a pending CIA irq might occur after we finish setting up our irq.
                          //we don't want that to happen.
  cli
  jmp *
}

fldirq: // first start this at raster $2f
{
  sta atemp

  inc $d020
  asl $d019

  lda nrlines: #0
  cmp #7
  lda $d012  // we need the $d012 value in both branches.
  bcs setirq
  
  // we can set d011 now and end the fld
  sec
  adc nrlines
  and #$07
  ora #$18
  sta $d011

  lda #<irq
  sta $fffe
  lda #>irq
  sta $ffff
  lda #$fa
  sta $d012

  dec $d020

  lda atemp: #0
  rti

setirq:
  // calc rasterline to trigger next irq
  // clc  // carry is alway set.. so abuse it
  adc #5  // add 5 instead of 6 because carry is set
  sta $d012

  //clc   // carry is now clear
  adc #1
  and #$07
  ora #$18
  sta $d011  // set $d011 to do an FLD

  lda nrlines // 6 lines less to fld..
  // we want to subtract 6, normally sec, sbc #6
  // but we abuse that carry is clear and sbc #5
  sbc #5
  sta nrlines

  dec $d020

  lda atemp
  rti
}

irq:
{
  sta atemp
  stx xtemp

  lda #$10
  sta $d011

  // constantly move down
  inc lines
  lda lines: #0
  and #$3f
  sta fldirq.nrlines

  ldx #40
  dex 
  bpl *-1

  lda #$18
  sta $d011

  lda #<fldirq
  sta $fffe
  lda #>fldirq
  sta $ffff
  lda #$2f
  sta $d012
  asl $d019

  lda atemp: #0
  ldx xtemp: #0
  rti
}